# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 14:40
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_model_changes.changes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('informacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('usos', models.CharField(blank=True, max_length=1000, null=True)),
                ('enlaces', models.CharField(blank=True, max_length=1000, null=True)),
                ('documentacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.IntegerField(choices=[(0, 'Borrador'), (1, 'Revisi\xf3n'), (2, 'Publica')], default=0)),
                ('licencia', models.CharField(blank=True, max_length=1000, null=True)),
                ('descarga_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('owner', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_mymodels', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='herramienta.Categoria')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
            },
            bases=(django_model_changes.changes.ChangesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HerramientaEdicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('informacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('usos', models.CharField(blank=True, max_length=1000, null=True)),
                ('enlaces', models.CharField(blank=True, max_length=1000, null=True)),
                ('documentacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('licencia', models.CharField(blank=True, max_length=1000, null=True)),
                ('descarga_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observacion')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramienta.Herramienta')),
            ],
            options={
                'verbose_name': 'Edicion de herramienta',
                'verbose_name_plural': 'Ediciones de herramienta',
            },
            bases=(django_model_changes.changes.ChangesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisiones',
            },
        ),
        migrations.AddField(
            model_name='herramientaedicion',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='herramienta.Revision', verbose_name='Estado de revision'),
        ),
        migrations.AddField(
            model_name='herramientaedicion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='herramienta.Categoria'),
        ),
        migrations.AddField(
            model_name='herramientaedicion',
            name='usuarioHerramienta',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_edit_model', to=settings.AUTH_USER_MODEL),
        ),
    ]
