# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0004_auto_20180330_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientaedicion',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
