# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0005_auto_20180331_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
