# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 04:55
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('herramienta', '0006_auto_20180331_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='herramienta/upload/')),
                ('owner', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_file', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo a cargar',
                'verbose_name_plural': 'Archivos cargados',
            },
        ),
    ]
