# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0008_herramientasporaprobar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herramientasporaprobar',
            options={'verbose_name': 'Herramienta por Aprobar', 'verbose_name_plural': 'Herramientas por Aprobar'},
        ),
    ]
