# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0010_auto_20180413_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='sistema_operativo',
            field=models.CharField(blank=True, choices=[(0, 'Windows'), (1, 'Linux'), (2, 'Mac')], default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramientaedicion',
            name='sistema_operativo',
            field=models.CharField(blank=True, choices=[(0, 'Windows'), (1, 'Linux'), (2, 'Mac')], default=0, max_length=1000, null=True),
        ),
    ]
