# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0010_auto_20180413_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='descarga_url',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='documentacion',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='enlaces',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='informacion',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='integracion_lms',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='licencia',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='sistema_operativo',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='usos',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='version',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramientaedicion',
            name='descarga_url',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramientaedicion',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramientaedicion',
            name='documentacion',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramientaedicion',
            name='enlaces',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramientaedicion',
            name='informacion',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramientaedicion',
            name='integracion_lms',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramientaedicion',
            name='licencia',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramientaedicion',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='herramientaedicion',
            name='sistema_operativo',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramientaedicion',
            name='usos',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='herramientaedicion',
            name='version',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
