# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0012_auto_20180415_1813'),
        ('herramienta', '0011_auto_20180415_1201'),
    ]

    operations = [
    ]
