# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herramienta', '0016_auto_20180515_0120'),
        ('herramienta', '0016_auto_20180517_1044'),
    ]

    operations = [
    ]
