# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='proyectos',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
